name: pragma_prueba
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4
  flutter_dotenv: ^5.0.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/launcher_icon.png"
  image_path_android: "assets/launcher_icon.png"
  adaptive_icon_foreground: "assets/launcher_icon.png"
  adaptive_icon_background: "#ffffff" 
  background_color_ios: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter:
  uses-material-design: true
  assets:
    - .env